### ISSUE TITLE
cant run cuz it caused bus error

### ISSUE THREAD

**Issue by Tezigudo** [oguzalp7/Draw_in_the_air#1]
I cant run the code it caused bus error and seegment error alternately

**Comment by oguzalp7** [comment]
Hi, it has been too long since I coded the project. I suggest you run the code as root in a Linux machine "sudo python3 virtual_pen.py" or in a Windows machine manner run it as administrator.  
ref: https://stackoverflow.com/questions/36970110/how-to-determine-the-cause-for-bus-error

The versions of Python and the modules on my pc are:
OpenCV: 4.4.0
Numpy: 1.21.4
Imutils: 0.5.3

Please let me know the results, so I can close the issue or find a solution :)

Best,
Alp

**Comment by Tezigudo** [comment]
ok

**Comment by Tezigudo** [comment]
<img width="580" alt="Screen Shot 2565-03-11 at 08 51 04" src="https://user-images.githubusercontent.com/80502090/157786678-586f05f3-80c0-47ea-b0d9-f9745c242083.png">

Its still not work

**Comment by oguzalp7** [comment]
Well, as far as I understand is the error occurs due to some pointer dereferencing; which is annoying in a Python code. 

Could you try to import modules one by one and run the code at a time? I believe that C/C++ based modules/libraries causing it. 

If you find a module/library that causing the problem; try delete and re-install it. 
Ref: https://github.com/mwaskom/seaborn/issues/2463

If that don't work you might need to give a shoot to mighty "memtester". I hope that won't be required 🤞🏻
Ref: https://stackoverflow.com/questions/9320875/mysterious-bus-error-with-web-twisted-code-works-on-one-server-and-does-not-o
